
theme = "everforest_dark"

[editor]
line-number = "relative"
color-modes = true
mouse = true
shell = ["zsh", "-c"]
auto-completion = true
auto-format = true
auto-pairs = true

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.indent-guides]
render = true
character = "⸽" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type", "position-percentage"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"


[keys.normal]
C-s = ":w"
C-q = ":q"
A-S-right = ":vsplit-new"
A-S-down = ":hsplit-new"